asyncapi: 2.4.0
info:
  title: 'OrderV2'
  version: 1.0.0
  description: Order Related Events
servers:
  test:
    url: test.mykafkacluster.org:8092
    protocol: kafka-secure
    description: Test broker
    security:
    - saslScram: []
channels:
  ids.order.submitted:
    description: The topic on which order complete event is publish.
    publish: 
      $ref: 'https://raw.githubusercontent.com/graj00/asyncapi/swaggerhub/avro/OrderHeader.avsc'
      traits: 
      - $ref: '#/components/operationTraits/kafka'
  ids.order.complete:
    description: The topic on which order complete event is publish.
    publish: 
      summary: Inform about Order Completion in IDS
      operationId: OrderComplete
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        traits:
          - $ref: '#/components/messageTraits/commonHeaders'
        payload:
          namespace: com.aligntech.orders
          type: record
          name: OrderSubmitted
          doc: This is avro schema for OrderSubmitted Event
          fields:
          - name: orderSubmittedDate
            type:
              type: long
              logicalType: timestamp-millis
            doc: Date when the Treatment form is submitted by the Doctor
          - name: orderSubmittedType
            type: string
            doc: Type of submission Online or Offline
          - name: orderSubmittedBy
            type: string
            doc: Treatment form submitted by user. User can be clinId or offline submitter
          - name: orderFeatures
            type:
              type: array
              items: string
            doc: Check for the features like Vivera Configurable for the order
      traits: 
      - $ref: '#/components/operationTraits/kafka'
components:
  messageTraits:
    commonHeaders:
      headers:
        type: object
        properties:
          orderId:
            type: integer
            description: "Order Id"
          clinId:
            type: string
            description: "Doctor ClinId"
          eventSource:
            type: string
            description: Source system generated this event, it can be IDS, MES, SIM
          eventDate:
            type: integer
            description: Timestamp when event is received by IDS(for external), generated by IDS(for internal).Modified_date from ordrestatushistory
        required:
          - orderId
          - clinId
          - eventSource
          - eventDate
  operationTraits:
    kafka:
      bindings:
        kafka:
          clientId:
            type: string
            enum: ['my-app-id']
  securitySchemes:
    saslScram:
      type: scramSha256
      description: Provide your username and password for SASL/SCRAM authentication