asyncapi: 2.4.0
info:
  title: 'Order'
  version: 1.0.0
  description: Order Related Events
servers:
  test:
    url: test.mykafkacluster.org:8092
    protocol: kafka-secure
    description: Test broker
    security:
    - saslScram: []
channels:
  ids.order.complete:
    description: The topic on which order complete event is publish.
    publish: 
      summary: Inform about Order Completion in IDS
      operationId: OrderComplete
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        traits:
          - $ref: '#/components/messageTraits/commonHeaders'
        payload:
          namespace: com.aligntech.orders
          type: record
          name: OrderComplete
          doc: This is avro schema for Order Complete Event
          fields:
          - name: orderShippedAt
            type:
              type: long
              logicalType: timestamp-millis
              doc: orderShippedDate of the order recevied from MES event
          - name: shipmentTrackingNumber
            type: string
            doc: Tracking Number for a shipment
          - name: shippingProvider
            type: string
            doc: shippingProvider Name like UPS, USPS, FedEx etc.
      traits: 
      - $ref: '#/components/operationTraits/kafka'
components:
  messageTraits:
    commonHeaders:
      headers:
        type: object
        properties:
          orderId:
            type: integer
            description: "Order Id"
          clinId:
            type: string
            description: "Doctor ClinId"
          eventSource:
            type: string
            description: Source system generated this event, it can be IDS, MES, SIM
          eventDate:
            type: integer
            description: Timestamp when event is received by IDS(for external), generated by IDS(for internal).Modified_date from ordrestatushistory
        required:
          - orderId
          - clinId
          - eventSource
          - eventDate
  operationTraits:
    kafka:
      bindings:
        kafka:
          clientId:
            type: string
            enum: ['my-app-id']
  securitySchemes:
    saslScram:
      type: scramSha256
      description: Provide your username and password for SASL/SCRAM authentication